import time
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QMainWindow,QApplication,QTableWidget
from PyQt5.QtGui import QIcon, QPixmap

class main_Window(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        
        #Giriş Frame
        self.welcomeFrame = QtWidgets.QFrame(self.centralwidget)
        self.welcomeFrame.setGeometry(QtCore.QRect(170, 10, 621, 531))
        self.welcomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcomeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.welcomeFrame.setObjectName("welcomeFrame")
        self.iconLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.iconLabel.setGeometry(QtCore.QRect(120, 40, 391, 381))
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap("icons/logo.jpeg"))
        self.iconLabel.setScaledContents(True)
        self.iconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.iconLabel.setObjectName("iconLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.welcomeLabel.setGeometry(QtCore.QRect(210, 440, 221, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 59, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 59, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 59, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 59, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.welcomeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName("welcomeLabel")
        
        #Kitaplar Frame
        self.booksFrame = QtWidgets.QFrame(self.centralwidget)
        self.booksFrame.setEnabled(True)
        self.booksFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.booksFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.booksFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.booksFrame.setObjectName("booksFrame")
        self.booksLabel = QtWidgets.QLabel(self.booksFrame)
        self.booksLabel.setGeometry(QtCore.QRect(20, 0, 250, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.booksLabel.setFont(font)
        self.booksLabel.setObjectName("welcomeLabel")
        self.booksTable = QtWidgets.QTableWidget(self.booksFrame)
        self.booksTable.setGeometry(QtCore.QRect(2, 75, 571, 379))
        self.booksTable.setObjectName("booksTable")
        
        self.booksTable.setColumnCount(3)
        self.booksTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 2, item)
        self.booksTable.setEditTriggers(QTableWidget.NoEditTriggers)
        
        self.takeBookButton = QtWidgets.QPushButton(self.booksFrame)
        self.takeBookButton.setGeometry(QtCore.QRect(470, 470, 111, 31))
        self.takeBookButton.setObjectName("takeBookButton")
        self.widget = QtWidgets.QWidget(self.booksFrame)
        self.widget.setGeometry(QtCore.QRect(230, 10, 351, 87))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLabel = QtWidgets.QLabel(self.widget)
        self.searchLabel.setObjectName("searchLabel")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchLabel.setFont(font)
        self.horizontalLayout.addWidget(self.searchLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.searchButton = QtWidgets.QPushButton(self.widget)
        self.searchButton.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('icons/search-icon.jpg'))
        self.searchButton.setIcon(self.icon)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.booksFrame.hide()
        
        #Kitaplarım Frame
        
        self.myBooksFrame = QtWidgets.QFrame(self.centralwidget)
        self.myBooksFrame.setEnabled(True)
        self.myBooksFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.myBooksFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.myBooksFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.myBooksFrame.setObjectName("myBooksFrame")
        self.myBooksLabel = QtWidgets.QLabel(self.myBooksFrame)
        self.myBooksLabel.setGeometry(QtCore.QRect(20, 0, 250, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.myBooksLabel.setFont(font)
        self.myBooksLabel.setObjectName("myBooksLable")
        self.myBooksTable = QtWidgets.QTableWidget(self.myBooksFrame)
        self.myBooksTable.setGeometry(QtCore.QRect(2, 75, 571, 379))
        self.myBooksTable.setObjectName("myBooksTable")
        
        self.myBooksTable.setColumnCount(3)
        self.myBooksTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 2, item)
        self.myBooksTable.setEditTriggers(QTableWidget.NoEditTriggers)
        
        self.leaveBookButton = QtWidgets.QPushButton(self.myBooksFrame)
        self.leaveBookButton.setGeometry(QtCore.QRect(470, 470, 111, 31))
        self.leaveBookButton.setObjectName("leaveBookButton")
        self.widget = QtWidgets.QWidget(self.myBooksFrame)
        self.widget.setGeometry(QtCore.QRect(230, 10, 351, 87))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLabel2 = QtWidgets.QLabel(self.widget)
        self.searchLabel2.setObjectName("searchLabel2")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchLabel2.setFont(font)
        self.horizontalLayout.addWidget(self.searchLabel2)
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout.addWidget(self.lineEdit2)
        self.searchButton2 = QtWidgets.QPushButton(self.widget)
        self.searchButton2.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('icons/search-icon.jpg'))
        self.searchButton2.setIcon(self.icon)
        self.searchButton2.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton2)
        self.myBooksFrame.hide()
        
        #Profil Frame
        self.profileFrame = QtWidgets.QFrame(self.centralwidget)
        self.profileFrame.setEnabled(True)
        self.profileFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.profileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileFrame.setObjectName("profileFrame")
        
        self.profileFrame.hide()
        
        
    
    
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 10, 21, 531))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 30, 141, 491))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.booksButton = QtWidgets.QPushButton(self.widget)
        self.booksButton.setObjectName("booksButton")
        self.verticalLayout.addWidget(self.booksButton)
        self.myBooksButton = QtWidgets.QPushButton(self.widget)
        self.myBooksButton.setObjectName("myBooksButton")
        self.verticalLayout.addWidget(self.myBooksButton)
        self.profileButton = QtWidgets.QPushButton(self.widget)
        self.profileButton.setObjectName("profileButton")
        self.verticalLayout.addWidget(self.profileButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout.addWidget(self.logoutButton)
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
        #Butonların Fonksiyonlar ile Bağlanması
        self.booksButton.clicked.connect(self.booksClick)
        self.myBooksButton.clicked.connect(self.myBooksClick)
        self.profileButton.clicked.connect(self.profileClick)
        self.logoutButton.clicked.connect(self.logoutClick)
        self.exitButton.clicked.connect(QApplication.instance().quit)

    
    
    #Kitaplar butonu fonskiyonu:
    def booksClick(self):
        print('Kitaplar Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.myBooksFrame.hide()
        self.profileFrame.hide()
        self.booksFrame.show()
        
    #Kitaplarım butonu fonksiyonu:
    def myBooksClick(self):
        print('Kitaplarım Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.booksFrame.hide()
        self.profileFrame.hide()
        self.myBooksFrame.show()
    
    #Profil butonu fonksiyonu:
    def profileClick(self):
        print('Profil Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.booksFrame.hide()
        self.myBooksFrame.hide()
        self.profileFrame.show()
        
    #Çıkış yapma butonu fonksiyonu
    def logoutClick(self):
        print('Çıkış Butonuna Tıklandı.')
        from loginWindow import login_Window
        self.startLoginWindow = login_Window()
        self.startLoginWindow.show()
        self.close()
        print('Giriş Ekranına Geçildi.')



    #İsimlendirme Fonksiyonu
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "ZBY Kütüphane Sistemi"))
        self.welcomeLabel.setText(_translate("MainWindow", "Hoş Geldiniz!"))
        
        #Menü Bar
        self.booksButton.setText(_translate("MainWindow", "Kitaplar"))
        self.myBooksButton.setText(_translate("MainWindow", "Kitaplarım"))
        self.profileButton.setText(_translate("MainWindow", "Profil"))
        self.logoutButton.setText(_translate("MainWindow", "Çıkış Yap"))
        self.exitButton.setText(_translate("MainWindow", "Uygulamayı Kapat"))
        
        #Kitaplar
        self.takeBookButton.setText(_translate("MainWindow", "Kitabı Al"))
        self.searchLabel.setText(_translate("MainWindow", "Arama: "))
        self.booksLabel.setText(_translate('MainWindow', 'Kitaplar'))
        
        #Kitaplarım
        self.leaveBookButton.setText(_translate("MainWindow", "Kitabı Bırak"))
        self.searchLabel2.setText(_translate("MainWindow", "Arama: "))
        self.myBooksLabel.setText(_translate('MainWindow', 'Kitaplarım'))
        
        item = self.booksTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.booksTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.booksTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yazar"))
        item = self.booksTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yayın Evi"))
        __sortingEnabled = self.booksTable.isSortingEnabled()
        self.booksTable.setSortingEnabled(False)
        item = self.booksTable.item(0, 0)
        item.setText(_translate("MainWindow", "Veronika Ölmek İstiyor"))
        item = self.booksTable.item(0, 1)
        item.setText(_translate("MainWindow", "Paulo Coelho"))
        item = self.booksTable.item(0, 2)
        item.setText(_translate("MainWindow", "Can Çağdaş"))
        self.booksTable.setSortingEnabled(__sortingEnabled)
        

        item = self.myBooksTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.myBooksTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.myBooksTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yazar"))
        item = self.myBooksTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yayın Evi"))
        __sortingEnabled = self.myBooksTable.isSortingEnabled()
        self.myBooksTable.setSortingEnabled(False)
        item = self.myBooksTable.item(0, 0)
        item.setText(_translate("MainWindow", "Veronika Ölmek İstiyor"))
        item = self.myBooksTable.item(0, 1)
        item.setText(_translate("MainWindow", "Paulo Coelho"))
        item = self.myBooksTable.item(0, 2)
        item.setText(_translate("MainWindow", "Can Çağdaş"))
        self.myBooksTable.setSortingEnabled(__sortingEnabled)