from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QMainWindow

class show_User_Info(QMainWindow):
    def __init__(self, current_data):
        super().__init__()

        self.setObjectName("showUserInfo")
        self.setFixedSize(600, 400)
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('../icons/logo.jpeg'))
        self.setWindowIcon(self.icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.userRoleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.userRoleEdit.setGeometry(QtCore.QRect(213, 44, 241, 22))
        self.userRoleEdit.setObjectName("userRoleEdit")
        self.userLabel = QtWidgets.QLabel(self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(100, 40, 82, 16))
        self.userLabel.setObjectName("userLabel")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(100, 73, 20, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.surnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.surnameLabel.setGeometry(QtCore.QRect(100, 102, 40, 16))
        self.surnameLabel.setObjectName("surnameLabel")
        self.tcNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.tcNoLabel.setGeometry(QtCore.QRect(100, 131, 77, 16))
        self.tcNoLabel.setObjectName("tcNoLabel")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(100, 160, 82, 16))
        self.idLabel.setObjectName("idLabel")
        self.phoneNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.phoneNoLabel.setGeometry(QtCore.QRect(100, 189, 106, 16))
        self.phoneNoLabel.setObjectName("phoneNoLabel")
        self.addressLabel = QtWidgets.QLabel(self.centralwidget)
        self.addressLabel.setGeometry(QtCore.QRect(100, 247, 38, 16))
        self.addressLabel.setObjectName("addressLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(100, 218, 38, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.idEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idEdit.setGeometry(QtCore.QRect(213, 160, 241, 22))
        self.idEdit.setObjectName("idEdit")
        self.surnameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.surnameEdit.setGeometry(QtCore.QRect(213, 102, 241, 22))
        self.surnameEdit.setObjectName("surnameEdit")
        self.tcNoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tcNoEdit.setGeometry(QtCore.QRect(213, 131, 241, 22))
        self.tcNoEdit.setObjectName("tcNoEdit")
        self.phoneNoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneNoEdit.setGeometry(QtCore.QRect(213, 189, 241, 22))
        self.phoneNoEdit.setObjectName("phoneNoEdit")
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(213, 73, 241, 22))
        self.nameEdit.setObjectName("nameEdit")
        self.addressEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.addressEdit.setGeometry(QtCore.QRect(213, 247, 241, 87))
        self.addressEdit.setObjectName("addressEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setGeometry(QtCore.QRect(213, 218, 241, 22))
        self.passwordEdit.setObjectName("passwordEdit")
        self.showPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.showPasswordButton.setGeometry(QtCore.QRect(455, 218, 28, 28))
        self.showPasswordButton.setObjectName("showPasswordButton")
        font2 = QtGui.QFont()
        font2.setPointSize(10)
        self.showPasswordButton.setText("👁️")
        self.showPasswordButton.setFont(font2)
        self.setCentralWidget(self.centralwidget)
        self.idEdit.setReadOnly(True)
        self.surnameEdit.setReadOnly(True)
        self.nameEdit.setReadOnly(True)
        self.addressEdit.setReadOnly(True)
        self.passwordEdit.setReadOnly(True)
        self.phoneNoEdit.setReadOnly(True)
        self.tcNoEdit.setReadOnly(True)
        self.userRoleEdit.setReadOnly(True)
        self.idEdit.setText(current_data[0])
        self.surnameEdit.setText(current_data[2])
        self.nameEdit.setText(current_data[1])
        self.addressEdit.setText(current_data[6])
        self.passwordEdit.setText(current_data[3])
        self.phoneNoEdit.setText(current_data[5])
        self.tcNoEdit.setText(current_data[7])
        self.userRoleEdit.setText(current_data[4])

        self.retranslateUi(self)
        self.showPasswordButton.clicked.connect(self.togglePasswordVisibility)
        QtCore.QMetaObject.connectSlotsByName(self)

    # Şifre göster butonu fonksiyonu
    def togglePasswordVisibility(self):
        if self.passwordEdit.echoMode() == QtWidgets.QLineEdit.Password:
            self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)

    def retranslateUi(self, showUserWindow):
        _translate = QtCore.QCoreApplication.translate
        showUserWindow.setWindowTitle(_translate("userAddWindow", "Kullanıcı Bilgileri"))
        self.userLabel.setText(_translate("userAddWindow", "Kullanıcı Türü:"))
        self.nameLabel.setText(_translate("userAddWindow", "Ad:"))
        self.surnameLabel.setText(_translate("userAddWindow", "Soyad:"))
        self.tcNoLabel.setText(_translate("userAddWindow", "TC Kimlik No:"))
        self.idLabel.setText(_translate("userAddWindow", "ID:"))
        self.phoneNoLabel.setText(_translate("userAddWindow", "Telefon Numarası:"))
        self.addressLabel.setText(_translate("userAddWindow", "Adres:"))
        self.passwordLabel.setText(_translate('userAddWindow', 'Şifre:'))