from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QMainWindow,QApplication,QTableWidget
from PyQt5.QtGui import QIcon, QPixmap

class user_Main_Window(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('icons/logo.jpeg'))
        self.setWindowIcon(self.icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        
        #Giriş Frame
        self.welcomeFrame = QtWidgets.QFrame(self.centralwidget)
        self.welcomeFrame.setGeometry(QtCore.QRect(170, 10, 621, 531))
        self.welcomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcomeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.welcomeFrame.setObjectName("welcomeFrame")
        self.iconLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.iconLabel.setGeometry(QtCore.QRect(120, 40, 391, 381))
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap("icons/logo.jpeg"))
        self.iconLabel.setScaledContents(True)
        self.iconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.iconLabel.setObjectName("iconLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.welcomeLabel.setGeometry(QtCore.QRect(210, 440, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName("welcomeLabel")
        
        #Kitaplar Frame
        self.booksFrame = QtWidgets.QFrame(self.centralwidget)
        self.booksFrame.setEnabled(True)
        self.booksFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.booksFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.booksFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.booksFrame.setObjectName("booksFrame")
        self.booksLabel = QtWidgets.QLabel(self.booksFrame)
        self.booksLabel.setGeometry(QtCore.QRect(20, 0, 250, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.booksLabel.setFont(font)
        self.booksLabel.setObjectName("welcomeLabel")
        self.booksTable = QtWidgets.QTableWidget(self.booksFrame)
        self.booksTable.setGeometry(QtCore.QRect(2, 75, 571, 379))
        self.booksTable.setObjectName("booksTable")
        
        self.booksTable.setColumnCount(3)
        self.booksTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setItem(0, 2, item)
        self.booksTable.setEditTriggers(QTableWidget.NoEditTriggers)
        
        self.takeBookButton = QtWidgets.QPushButton(self.booksFrame)
        self.takeBookButton.setGeometry(QtCore.QRect(470, 470, 111, 31))
        self.takeBookButton.setObjectName("takeBookButton")
        self.widget = QtWidgets.QWidget(self.booksFrame)
        self.widget.setGeometry(QtCore.QRect(230, 10, 351, 87))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLabel = QtWidgets.QLabel(self.widget)
        self.searchLabel.setObjectName("searchLabel")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchLabel.setFont(font)
        self.horizontalLayout.addWidget(self.searchLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.searchButton = QtWidgets.QPushButton(self.widget)
        self.searchButton.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('icons/search-icon.jpg'))
        self.searchButton.setIcon(self.icon)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.booksFrame.hide()
        
        #Kitaplarım Frame
        
        self.myBooksFrame = QtWidgets.QFrame(self.centralwidget)
        self.myBooksFrame.setEnabled(True)
        self.myBooksFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.myBooksFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.myBooksFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.myBooksFrame.setObjectName("myBooksFrame")
        self.myBooksLabel = QtWidgets.QLabel(self.myBooksFrame)
        self.myBooksLabel.setGeometry(QtCore.QRect(20, 0, 250, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.myBooksLabel.setFont(font)
        self.myBooksLabel.setObjectName("myBooksLable")
        self.myBooksTable = QtWidgets.QTableWidget(self.myBooksFrame)
        self.myBooksTable.setGeometry(QtCore.QRect(2, 75, 571, 379))
        self.myBooksTable.setObjectName("myBooksTable")
        
        self.myBooksTable.setColumnCount(3)
        self.myBooksTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myBooksTable.setItem(0, 2, item)
        self.myBooksTable.setEditTriggers(QTableWidget.NoEditTriggers)
        
        
        
        self.leaveBookButton = QtWidgets.QPushButton(self.myBooksFrame)
        self.leaveBookButton.setGeometry(QtCore.QRect(470, 470, 111, 31))
        self.leaveBookButton.setObjectName("leaveBookButton")
        self.widget = QtWidgets.QWidget(self.myBooksFrame)
        self.widget.setGeometry(QtCore.QRect(230, 10, 351, 87))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLabel2 = QtWidgets.QLabel(self.widget)
        self.searchLabel2.setObjectName("searchLabel2")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchLabel2.setFont(font)
        self.horizontalLayout.addWidget(self.searchLabel2)
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout.addWidget(self.lineEdit2)
        self.searchButton2 = QtWidgets.QPushButton(self.widget)
        self.searchButton2.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap('icons/search-icon.jpg'))
        self.searchButton2.setIcon(self.icon)
        self.searchButton2.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton2)
        self.myBooksFrame.hide()
        
        #Profil Frame
        self.profileFrame = QtWidgets.QFrame(self.centralwidget)
        self.profileFrame.setEnabled(True)
        self.profileFrame.setGeometry(QtCore.QRect(180, 20, 591, 511))
        self.profileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.checkLabel = QtWidgets.QLabel(self.profileFrame)
        self.checkLabel.setGeometry(QtCore.QRect(396, 430, 28, 28))
        self.checkLabel.setObjectName('checkLabel')
        self.checkLabel.setText('')
        self.checkLabel.setPixmap(QtGui.QPixmap("icons/checkMark.jpg"))
        self.checkLabel.setScaledContents(True)
        self.checkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkLabel.hide()
        self.profileLabel = QtWidgets.QLabel(self.profileFrame)
        self.profileLabel.setGeometry(QtCore.QRect(20, 0, 250, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.profileLabel.setFont(font)
        self.profileLabel.setObjectName("profileLabel")
        self.profileEditButton = QtWidgets.QPushButton(self.profileFrame)
        self.profileEditButton.setGeometry(QtCore.QRect(210, 430, 93, 28))
        self.profileEditButton.setObjectName("profileEditButton")
        self.profileSaveButton = QtWidgets.QPushButton(self.profileFrame)
        self.profileSaveButton.setGeometry(QtCore.QRect(303, 430, 93, 28))
        self.profileSaveButton.setObjectName('profileSaveButton')
        self.widget = QtWidgets.QWidget(self.profileFrame)
        self.widget.setGeometry(QtCore.QRect(60, 100, 391, 301))
        self.widget.setObjectName("widget")
        self.profileLayout = QtWidgets.QGridLayout(self.widget)
        self.profileLayout.setContentsMargins(0, 0, 0, 0)
        self.profileLayout.setObjectName("profileLayout")
        self.addressLabel = QtWidgets.QLabel(self.widget)
        self.addressLabel.setObjectName("addressLabel")
        self.profileLayout.addWidget(self.addressLabel, 6, 0, 1, 1)
        self.surnameEditLine = QtWidgets.QLineEdit(self.widget)
        self.surnameEditLine.setObjectName("surnameEditLine")
        self.surnameEditLine.setReadOnly(True)
        self.profileLayout.addWidget(self.surnameEditLine, 2, 1, 1, 1)
        self.tcNoLabel = QtWidgets.QLabel(self.widget)
        self.tcNoLabel.setObjectName("tcNoLabel")
        self.profileLayout.addWidget(self.tcNoLabel, 3, 0, 1, 1)
        self.phoneNoLabel = QtWidgets.QLabel(self.widget)
        self.phoneNoLabel.setObjectName("phoneNoLabel")
        self.profileLayout.addWidget(self.phoneNoLabel, 5, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLineEdit.setReadOnly(True)
        self.profileLayout.addWidget(self.nameLineEdit, 1, 1, 1, 1)
        self.phoneNoEditLine = QtWidgets.QLineEdit(self.widget)
        self.phoneNoEditLine.setObjectName("phoneNoEditLine")
        self.phoneNoEditLine.setReadOnly(True)
        self.profileLayout.addWidget(self.phoneNoEditLine, 5, 1, 1, 1)
        self.tcNoEditLine = QtWidgets.QLineEdit(self.widget)
        self.tcNoEditLine.setObjectName("tcNoEditLine")
        self.tcNoEditLine.setReadOnly(True)
        self.profileLayout.addWidget(self.tcNoEditLine, 3, 1, 1, 1)
        self.addressEdit = QtWidgets.QTextEdit(self.widget)
        self.addressEdit.setObjectName("addressEdit")
        self.addressEdit.setReadOnly(True)
        self.profileLayout.addWidget(self.addressEdit, 6, 1, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.widget)
        self.surnameLabel.setObjectName("surnameLabel")
        self.profileLayout.addWidget(self.surnameLabel, 2, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.widget)
        self.nameLabel.setObjectName("nameLabel")
        self.profileLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.widget)
        self.idLabel.setObjectName("idLabel")
        self.profileLayout.addWidget(self.idLabel, 0, 0, 1, 1)
        self.idLineEdit = QtWidgets.QLineEdit(self.widget)
        self.idLineEdit.setObjectName("idLineEdit")
        self.idLineEdit.setReadOnly(True)
        self.profileLayout.addWidget(self.idLineEdit, 0, 1, 1, 1)
        self.birthLabel = QtWidgets.QLabel(self.widget)
        self.birthLabel.setObjectName("birthLable")
        self.profileLayout.addWidget(self.birthLabel, 4, 0, 1, 1)
        self.birthEdit = QtWidgets.QDateEdit(self.widget)
        self.birthEdit.setObjectName("birthEdit")
        self.birthEdit.setReadOnly(True)
        self.profileLayout.addWidget(self.birthEdit, 4, 1, 1, 1)
        self.profileFrame.hide()
        
        
    
    
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 10, 21, 531))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 30, 141, 491))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.booksButton = QtWidgets.QPushButton(self.widget)
        self.booksButton.setObjectName("booksButton")
        self.verticalLayout.addWidget(self.booksButton)
        self.myBooksButton = QtWidgets.QPushButton(self.widget)
        self.myBooksButton.setObjectName("myBooksButton")
        self.verticalLayout.addWidget(self.myBooksButton)
        self.profileButton = QtWidgets.QPushButton(self.widget)
        self.profileButton.setObjectName("profileButton")
        self.verticalLayout.addWidget(self.profileButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout.addWidget(self.logoutButton)
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
        #Butonların Fonksiyonlar ile Bağlanması
        self.booksButton.clicked.connect(self.booksClick)
        self.myBooksButton.clicked.connect(self.myBooksClick)
        self.profileButton.clicked.connect(self.profileClick)
        self.logoutButton.clicked.connect(self.logoutClick)
        self.profileEditButton.clicked.connect(self.profileEditClick)
        self.profileSaveButton.clicked.connect(self.profileSaveClick)
        self.takeBookButton.clicked.connect(self.takeBookClick)
        self.leaveBookButton.clicked.connect(self.leaveBookClick)
        self.exitButton.clicked.connect(QApplication.instance().quit)
    
    
    #Kitaplar butonu fonskiyonu:
    def booksClick(self):
        print('Kitaplar Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.myBooksFrame.hide()
        self.profileFrame.hide()
        self.booksFrame.show()
        
    #Kitaplarım butonu fonksiyonu:
    def myBooksClick(self):
        print('Kitaplarım Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.booksFrame.hide()
        self.profileFrame.hide()
        self.myBooksFrame.show()
    
    #Profil butonu fonksiyonu:
    def profileClick(self):
        print('Profil Butonuna Tıklandı.')
        self.welcomeFrame.hide()
        self.booksFrame.hide()
        self.myBooksFrame.hide()
        self.profileFrame.show()
        
    #Çıkış yapma butonu fonksiyonu
    def logoutClick(self):
        print('Çıkış Butonuna Tıklandı.')
        from loginWindow import login_Window
        self.startLoginWindow = login_Window()
        self.startLoginWindow.show()
        self.close()
        print('Giriş Ekranına Geçildi.')
    
    #Profil düzenleme butonu fonksiyonu
    def profileEditClick(self):
        print('Profil Düzenleme Butonuna Tıklandı.')
        self.nameLineEdit.setReadOnly(False)
        self.surnameEditLine.setReadOnly(False)
        self.phoneNoEditLine.setReadOnly(False)
        self.addressEdit.setReadOnly(False)
        self.checkLabel.hide()
    
    #Kaydetme butonu fonksiyonu
    def profileSaveClick(self):
        print('Profili Kaydet Butonuna Tıklandı.')
        self.nameLineEdit.setReadOnly(True)
        self.surnameEditLine.setReadOnly(True)
        self.phoneNoEditLine.setReadOnly(True)
        self.addressEdit.setReadOnly(True)
        self.checkLabel.show()
    
    #Kitap alma butonu fonksiyonu
    def takeBookClick(self):
        print('Kitap Alma Butonuna Tıklandı.')
    
    #Kitap bırakma butonu fonksiyonu
    def leaveBookClick(self):
        print('Kitap Bırakma Butonun Tıklandı.')


    #İsimlendirme Fonksiyonu
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "ZBY Kütüphane Sistemi"))
        self.welcomeLabel.setText(_translate("MainWindow", "Hoş Geldiniz!"))
        
        #Menü Bar
        self.booksButton.setText(_translate("MainWindow", "Kitaplar"))
        self.myBooksButton.setText(_translate("MainWindow", "Kitaplarım"))
        self.profileButton.setText(_translate("MainWindow", "Profil"))
        self.logoutButton.setText(_translate("MainWindow", "Çıkış Yap"))
        self.exitButton.setText(_translate("MainWindow", "Uygulamayı Kapat"))
        
        #Kitaplar
        self.takeBookButton.setText(_translate("MainWindow", "Kitabı Al"))
        self.searchLabel.setText(_translate("MainWindow", "Arama: "))
        self.booksLabel.setText(_translate('MainWindow', 'Kitaplar'))
        
        #Kitaplarım
        self.leaveBookButton.setText(_translate("MainWindow", "Kitabı Bırak"))
        self.searchLabel2.setText(_translate("MainWindow", "Arama: "))
        self.myBooksLabel.setText(_translate('MainWindow', 'Kitaplarım'))
        
        item = self.booksTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.booksTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.booksTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yazar"))
        item = self.booksTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yayın Evi"))
        __sortingEnabled = self.booksTable.isSortingEnabled()
        self.booksTable.setSortingEnabled(False)
        item = self.booksTable.item(0, 0)
        item.setText(_translate("MainWindow", "Veronika Ölmek İstiyor"))
        item = self.booksTable.item(0, 1)
        item.setText(_translate("MainWindow", "Paulo Coelho"))
        item = self.booksTable.item(0, 2)
        item.setText(_translate("MainWindow", "Can Çağdaş"))
        self.booksTable.setSortingEnabled(__sortingEnabled)
        

        item = self.myBooksTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.myBooksTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.myBooksTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yazar"))
        item = self.myBooksTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yayın Evi"))
        __sortingEnabled = self.myBooksTable.isSortingEnabled()
        self.myBooksTable.setSortingEnabled(False)
        item = self.myBooksTable.item(0, 0)
        item.setText(_translate("MainWindow", "Veronika Ölmek İstiyor"))
        item = self.myBooksTable.item(0, 1)
        item.setText(_translate("MainWindow", "Paulo Coelho"))
        item = self.myBooksTable.item(0, 2)
        item.setText(_translate("MainWindow", "Can Çağdaş"))
        self.myBooksTable.setSortingEnabled(__sortingEnabled)
        self.profileLabel.setText(_translate("MainWindow", "Profiliniz"))
        self.profileEditButton.setText(_translate("MainWindow", "Düzenle"))
        self.addressLabel.setText(_translate("MainWindow", "Adres: "))
        self.tcNoLabel.setText(_translate("MainWindow", "Kimlik No:"))
        self.phoneNoLabel.setText(_translate("MainWindow", "Telefon Numarası: "))
        self.surnameLabel.setText(_translate("MainWindow", "Soyad:"))
        self.nameLabel.setText(_translate("MainWindow", "İsim:"))
        self.idLabel.setText(_translate("MainWindow", "ID :"))
        self.birthLabel.setText(_translate("MainWindow", "Doğum Tarihi:"))
        self.profileSaveButton.setText(_translate('MainWindow', 'Kaydet'))